### PR TITLE
updated

### PR DESCRIPTION
**Pull request by edneyhelene**
update to add missing extensions

### CODE REVIEW

**Comment by shantigilbert** [comment]
When you add the extension please use both lower and uppercase, this is kissing uppercase .ZIP

**Comment by edneyhelene** [comment]
Sure will do \o

**Comment by shantigilbert** [comment]
That las commit is not necessary, the fix was already applied, this actually breaks it

**Comment by shantigilbert** [comment]
Open a PR per change please, don't mix all the changes into one

**Pull request closed without merging**
