### PR TITLE
We can use /dev/input/jsX now.

### PR DESCRIPTION
**Pull request by BetaXOi**
Signed-off-by: Ning Bo <n.b@live.com>

### CODE REVIEW

**Comment by shantigilbert** [comment]
Thank you!

So if I understand correctly, this can now be use by either /dev/input/eventx or by /dev/input/jsx ?

**Comment by BetaXOi** [comment]
Yes, It is.

**Comment by shantigilbert** [comment]
Thank you, it works perfectly!

**Comment by shantigilbert** [comment]
@BetaXOi are you up for another task? 

evkill works almost perfect, except I have to manually configure it for each controller for it to work, do you think there might be a way to use retroarch joypad config file to select certain buttons? 

This is a sample

```
input_device = "HORI CO.,LTD. HORIPAD S"
input_driver = "udev"
input_r_y_plus_axis = "+3"
input_l3_btn = "10"
input_r_x_minus_axis = "-2"
input_l_btn = "4"
input_load_state_btn = "4"
input_start_btn = "9"
input_exit_emulator_btn = "9"
input_l_y_minus_axis = "-1"
input_up_btn = "h0up"
input_volume_up_btn_btn = "h0up"
input_r_y_minus_axis = "-3"
input_a_btn = "2"
input_b_btn = "1"
input_reset_btn = "1"
input_enable_hotkey_btn = "12"
input_down_btn = "h0down"
input_volume_down_btn_btn = "h0down"
input_l_x_plus_axis = "+0"
input_l_y_plus_axis = "+1"
input_r_btn = "5"
input_save_state_btn = "5"
input_r2_btn = "7"
input_hold_fast_forward_btn = "7"
input_r3_btn = "11"
input_fps_toggle_btn = "11"
input_right_btn = "h0right"
input_state_slot_increase_btn = "h0right"
input_x_btn = "3"
input_menu_toggle_btn = "3"
input_select_btn = "8"
input_l_x_minus_axis = "-0"
input_y_btn = "0"
input_left_btn = "h0left"
input_state_slot_decrease_btn = "h0left"
input_r_x_plus_axis = "+2"
input_l2_btn = "6"
input_rewind_btn = "6"
```
in this case it would be interesting to pick up or convert the values from `input_enable_hotkey_btn = "12"` and `input_exit_emulator_btn = "9"` so that they work on evkill.


Or it could also be froms Emulationstation's es_input.cfg
```
<inputConfig type="joystick" deviceName="HORI CO.,LTD. HORIPAD S" deviceGUID="030000000d0f0000c100000011010000">
    <input name="rightanalogdown" type="axis" id="3" value="1"/>
    <input name="rightanalogleft" type="axis" id="2" value="-1"/>
    <input name="leftshoulder" type="button" id="4" value="1"/>
    <input name="start" type="button" id="9" value="1"/>
    <input name="leftanalogup" type="axis" id="1" value="-1"/>
    <input name="up" type="hat" id="0" value="1"/>
    <input name="rightanalogup" type="axis" id="3" value="-1"/>
    <input name="a" type="button" id="2" value="1"/>
    <input name="b" type="button" id="1" value="1"/>
    <input name="hotkeyenable" type="button" id="12" value="1"/>
    <input name="down" type="hat" id="0" value="4"/>
    <input name="leftanalogright" type="axis" id="0" value="1"/>
    <input name="leftanalogdown" type="axis" id="1" value="1"/>
    <input name="rightshoulder" type="button" id="5" value="1"/>
    <input name="righttrigger" type="button" id="7" value="1"/>
    <input name="right" type="hat" id="0" value="2"/>
    <input name="x" type="button" id="3" value="1"/>
    <input name="select" type="button" id="8" value="1"/>
    <input name="leftanalogleft" type="axis" id="0" value="-1"/>
    <input name="y" type="button" id="0" value="1"/>
    <input name="left" type="hat" id="0" value="8"/>
    <input name="rightanalogright" type="axis" id="2" value="1"/>
    <input name="lefttrigger" type="button" id="6" value="1"/>
  </inputConfig>
```

You think its possible?

**Comment by BetaXOi** [comment]
Yes, it's possible, i'll do it in this weekend.
________________________________
发件人: shantigilbert <notifications@github.com>
发送时间: 2019年8月2日 6:19
收件人: shantigilbert/EmuELEC <EmuELEC@noreply.github.com>
抄送: BetaXOi <n.b@live.com>; Mention <mention@noreply.github.com>
主题: Re: [shantigilbert/EmuELEC] We can use /dev/input/jsX now. (#30)


@BetaXOi<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBetaXOi&data=02%7C01%7C%7Cd3aa466a92b14e82516e08d7171161e3%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637003235734564630&sdata=F3EMIhg1pOyOPOJk35Bla8WkBbX04XOF86kgFhsflc4%3D&reserved=0> are you up for another task?

evkill works almost perfect, except I have to manually configure it for each controller for it to work, do you think there might be a way to use retroarch joypad config file to select certain buttons?

This is a sample

input_device = "HORI CO.,LTD. HORIPAD S"
input_driver = "udev"
input_r_y_plus_axis = "+3"
input_l3_btn = "10"
input_r_x_minus_axis = "-2"
input_l_btn = "4"
input_load_state_btn = "4"
input_start_btn = "9"
input_exit_emulator_btn = "9"
input_l_y_minus_axis = "-1"
input_up_btn = "h0up"
input_volume_up_btn_btn = "h0up"
input_r_y_minus_axis = "-3"
input_a_btn = "2"
input_b_btn = "1"
input_reset_btn = "1"
input_enable_hotkey_btn = "12"
input_down_btn = "h0down"
input_volume_down_btn_btn = "h0down"
input_l_x_plus_axis = "+0"
input_l_y_plus_axis = "+1"
input_r_btn = "5"
input_save_state_btn = "5"
input_r2_btn = "7"
input_hold_fast_forward_btn = "7"
input_r3_btn = "11"
input_fps_toggle_btn = "11"
input_right_btn = "h0right"
input_state_slot_increase_btn = "h0right"
input_x_btn = "3"
input_menu_toggle_btn = "3"
input_select_btn = "8"
input_l_x_minus_axis = "-0"
input_y_btn = "0"
input_left_btn = "h0left"
input_state_slot_decrease_btn = "h0left"
input_r_x_plus_axis = "+2"
input_l2_btn = "6"
input_rewind_btn = "6"


in this case it would be interesting to pick up or convert the values from input_enable_hotkey_btn = "12" and input_exit_emulator_btn = "9" so that they work on evkill.

Or it could also be froms Emulationstation's es_input.cfg

<inputConfig type="joystick" deviceName="HORI CO.,LTD. HORIPAD S" deviceGUID="030000000d0f0000c100000011010000">
    <input name="rightanalogdown" type="axis" id="3" value="1"/>
    <input name="rightanalogleft" type="axis" id="2" value="-1"/>
    <input name="leftshoulder" type="button" id="4" value="1"/>
    <input name="start" type="button" id="9" value="1"/>
    <input name="leftanalogup" type="axis" id="1" value="-1"/>
    <input name="up" type="hat" id="0" value="1"/>
    <input name="rightanalogup" type="axis" id="3" value="-1"/>
    <input name="a" type="button" id="2" value="1"/>
    <input name="b" type="button" id="1" value="1"/>
    <input name="hotkeyenable" type="button" id="12" value="1"/>
    <input name="down" type="hat" id="0" value="4"/>
    <input name="leftanalogright" type="axis" id="0" value="1"/>
    <input name="leftanalogdown" type="axis" id="1" value="1"/>
    <input name="rightshoulder" type="button" id="5" value="1"/>
    <input name="righttrigger" type="button" id="7" value="1"/>
    <input name="right" type="hat" id="0" value="2"/>
    <input name="x" type="button" id="3" value="1"/>
    <input name="select" type="button" id="8" value="1"/>
    <input name="leftanalogleft" type="axis" id="0" value="-1"/>
    <input name="y" type="button" id="0" value="1"/>
    <input name="left" type="hat" id="0" value="8"/>
    <input name="rightanalogright" type="axis" id="2" value="1"/>
    <input name="lefttrigger" type="button" id="6" value="1"/>
  </inputConfig>


You think its possible?

―

**Comment by shantigilbert** [comment]
Thanks! I pushed a commit that enables ee_kill.conf the user can (hopefully) then choose which gamepad can be used to kill emus. 

https://github.com/shantigilbert/EmuELEC/blob/a1f7fc8d4e2064bc9448411f64aaf50c1dbb49a3/packages/sx05re/emuelec/config/ee_kill.conf

**Pull request merged**
