### PR TITLE
evkill: Add support for loading configuration from file and monitoring change.

### PR DESCRIPTION
**Pull request by BetaXOi**
We can load configration from file specified now.
eg: evkill -f ee_kill.conf retroarch

Signed-off-by: Ning Bo <n.b@live.com>

### CODE REVIEW

**Comment by shantigilbert** [comment]
@BetaXOi  Sorry to be a pain , but after trying this, I might be wrong but this will not read the info from the .cfg file in /tmp/joypads?, my idea was to have the same keys used in emulationstation or retroarch be the ones to be used here, as I understand this change only makes it so that you can read the config from ee_kill.cfg, but you would still have to run jstest to find the correct keys, right? 

Do you think there might be a way to use retroarch joypad config file to select certain buttons? 

This is a sample

```
input_device = "HORI CO.,LTD. HORIPAD S"
input_driver = "udev"
input_r_y_plus_axis = "+3"
input_l3_btn = "10"
input_r_x_minus_axis = "-2"
input_l_btn = "4"
input_load_state_btn = "4"
input_start_btn = "9"
input_exit_emulator_btn = "9"
input_l_y_minus_axis = "-1"
input_up_btn = "h0up"
input_volume_up_btn_btn = "h0up"
input_r_y_minus_axis = "-3"
input_a_btn = "2"
input_b_btn = "1"
input_reset_btn = "1"
input_enable_hotkey_btn = "12"
input_down_btn = "h0down"
input_volume_down_btn_btn = "h0down"
input_l_x_plus_axis = "+0"
input_l_y_plus_axis = "+1"
input_r_btn = "5"
input_save_state_btn = "5"
input_r2_btn = "7"
input_hold_fast_forward_btn = "7"
input_r3_btn = "11"
input_fps_toggle_btn = "11"
input_right_btn = "h0right"
input_state_slot_increase_btn = "h0right"
input_x_btn = "3"
input_menu_toggle_btn = "3"
input_select_btn = "8"
input_l_x_minus_axis = "-0"
input_y_btn = "0"
input_left_btn = "h0left"
input_state_slot_decrease_btn = "h0left"
input_r_x_plus_axis = "+2"
input_l2_btn = "6"
input_rewind_btn = "6"
```
in this case it would be interesting to pick up or convert the values from `input_enable_hotkey_btn = "12"` and `input_exit_emulator_btn = "9"` so that they work on evkill.

On ee_kill.cfg the idea was to just read this var: EE_GAMEPAD and based on that read the file in /tmp/joypads and then convert the buttons from  `input_enable_hotkey_btn`  and `input_exit_emulator_btn` so that they work on evkill.
This way users will only have to configure their gamepad once and the "kill" command would work anywhere, do I make any sense? 

Thanks and sorry for the bother!

**Comment by BetaXOi** [comment]
I see, get gamepad name from ee_kill.conf, then get botton number from /tmp/joypads/@name

```
# cat "/tmp/joypads/$(cat ee_kill.conf |grep EE_GAMEPAD |awk -F= '{print $2}' |tr -d \")" |grep -E 'hotkey_btn|ex
it_emulator_btn'                                                                                                              
input_exit_emulator_btn = "11"
input_enable_hotkey_btn = "12"
```

then convert botton number to input event code for `evkill`, right?

```
$ cat /usr/include/linux/input-event-codes.h |grep BTN_GAMEPAD
#define BTN_GAMEPAD             0x130
$ echo $((16#130 + 10#12))
316
$ echo $((16#130 + 10#11))
315
```

so, `evkill` needs to monitor `ee_kill.conf` and `/tmp/joypads/@name` two file also.

**Comment by shantigilbert** [comment]
Yes, it gets the name of the gamepad configuration (EE_GAMEPAD) they want to use from ee_kill.cfg and the buttons they get from the configuration and convert to event codes for evkill exactly. 

1.- Read the gamepad configuration file from `ee_kill.cfg`  (EE_GAMEPAD)
2.- Read the `input_exit_emulator_btn` and `input_enable_hotkey_btn` and convert to event codes (EE_KILLKEYS)
3.-  Using something like `cat /proc/bus/input/devices` we could get the /dev/input/eventX (EE_KILLDEV)
4.- Use that information to create the keycombo to kill the given program in the argument.

This would make the program perfect!

**Comment by BetaXOi** [comment]
I am confused. Who created and modified the file `/emuelec/configs/ee_kill.cfg`? Does `ev_kill` need to maintain the contents of this file?

If `EE_KILLKEYS` already exists in the configuration file, why do I need to read `input_exit_emulator_btn` and `input_enable_hotkey_btn` from another configuration file and convert it? Why not use `EE_KILLKEYS` directly?

**Comment by shantigilbert** [comment]
EE_KILLKEYS will be automatically changed depending on the configuration file, the only thing in the configuration file that will matter for the program is the name of the gamepad (EE_GAMEPAD).
everything else should be automatically filled from the /tmp/joypad/@ files (input_exit_emulator_btn and input_enable_hotkey_btn)

The reason being that if we get the keys automatically we only have to set it once in Emulationstation, and this will work on the gamepad specified in the configuration without having to get the event codes from evtest making it automatically to configure.

**Comment by shantigilbert** [comment]
Actually with the scripts you posted before I came up with this, might work with what you already have 

```
#!/bin/sh

EE_GAMEPAD="/tmp/joypads/$(cat /emuelec/configs/ee_kill.cfg |grep EE_GAMEPAD |awk -F= '{print $2}' |tr -d \")"

KEY1=$(cat "$EE_GAMEPAD" |grep -E 'hotkey_btn' | cut -d '"' -f2)
KEY2=$(cat "$EE_GAMEPAD" |grep -E 'input_exit_emulator_btn' | cut -d '"' -f2)

KEY1=$(echo $((16#130 + 10#$KEY1)))
KEY2=$(echo $((16#130 + 10#$KEY2)))

EE_KILLKEYS="$KEY1+$KEY2"

#update /emuelec/config/ee_kill.cfg with the corresponding keys
sed -i "s/EE_KILLKEYS=".*"/EE_KILLKEYS=\"${EE_KILLKEYS}\"/g" /emuelec/configs/ee_kill.cfg

## Would be great if we could get the eventX from /proc/bus/input/devices so we could update EE_KILLDEV as well, maybe using awk?
#DEVICE=$(cat "$EE_GAMEPAD" |grep -E 'input_device' | cut -d '"' -f2)
#EE_GAMEPAD="${EE_GAMEPAD%.*}"
#echo "$DEVICE"

```

**Comment by BetaXOi** [comment]
I have some questions about the life cycle of `evkill` and who will modify the `ev_kill.cfg` file.

- `evkill` starts with `retroarch` and automatically quits when killing retroarch?
- If `retroarch` is actively terminated, `evkill` automatically exits with it also?
- you said that `EE_KILLKEYS` will be automatically changed according to the configuration file, who is responsible for doing this?

**Comment by shantigilbert** [comment]
Evkill gets called by emuelecrunemu.sh for emulators that required and it dies after sending killall. (retroarch does not require it) 

And you are right, I was complicating stuff, I think it's best to handle that with a script like the one I posted before, this script can then be called after input configuration in emulationstation, so for now evkill.c should work. We just need to fix the typo

**Comment by shantigilbert** [comment]
Just one question, does the event code conversion formula works on all gamepads? Do you know?

**Comment by BetaXOi** [comment]
Yes, I think all gamepads should follow the definition in /usr/include/linux/input-event-codes.h

**Comment by BetaXOi** [comment]
There is another thing, in addition to fixing the typo, when `EE_KILLDEV` changes, `evkill` needs to reopen the 'jsx' device, I forgot to implement this part of the logic.

I will update the submission later.

**Comment by shantigilbert** [comment]
With the information you gave me made this script that in combination with evkill should do exactly what I needed, I am pretty sure I can't be cleaned up or optimized, but this is as fast as my skill will let me.

```
#!/bin/sh


# IMPORTANT: js0 is always used as default, but you can change this in ee_kill.cfg

# Update /emuelec/config/ee_kill.cfg with the corresponding gamepad config
EE_DEV="$(cat /emuelec/configs/ee_kill.cfg |grep EE_KILLDEV |awk -F= '{print $2}' | tr -d \")"

for file in /tmp/joypads/*.cfg; do
file2=$(basename "$file")
EE_GAMEPAD="${file2//[ ()@$,]/_}"
EE_GAMEPAD="${EE_GAMEPAD%.*}"

if ls -la /dev/input/by-id/ | grep $EE_GAMEPAD | grep $EE_DEV > /dev/null; then
#sed -i "s/EE_GAMEPAD=".*"/EE_GAMEPAD=\"${file2}\"/g" /emuelec/configs/ee_kill.cfg
break
fi
done

# Update /emuelec/config/ee_kill.cfg with the corresponding keys

EE_GAMEPAD="/tmp/joypads/$file2"
KEY1=$(cat "$EE_GAMEPAD" | grep -E 'hotkey_btn' | cut -d '"' -f2)
KEY2=$(cat "$EE_GAMEPAD" | grep -E 'input_exit_emulator_btn' | cut -d '"' -f2)
KEY1=$(echo $((16#130 + 10#$KEY1)))
KEY2=$(echo $((16#130 + 10#$KEY2)))
EE_KILLKEYS="$KEY1+$KEY2"
sed -i "s/EE_KILLKEYS=".*"/EE_KILLKEYS=\"${EE_KILLKEYS}\"/g" /emuelec/configs/ee_kill.cfg

DEVICE=$(cat "$EE_GAMEPAD" | grep -E 'input_device' | cut -d '"' -f2)

echo "Kill combo set to $EE_KILLKEYS from $EE_GAMEPAD Dev: $EE_DEV"
```
Thanks for all of your help!

**Comment by shantigilbert** [comment]
Also since with the information you provided we can get all the info and pass it to the current evkill, I am not sure this PR is needed anymore?

**Comment by BetaXOi** [comment]
Very happy that the problem has been solved.

**Comment by shantigilbert** [comment]
Thanks to you @BetaXOi

**Comment by shantigilbert** [comment]
@BetaXOi 

Sorry to bother you again.

Do you know another way to convert the keycodes other than this?

```
KEY1=$(echo $((16#130 + 10#$KEY1)))
KEY2=$(echo $((16#130 + 10#$KEY2)))
```

it seems most controllers fail :( 

Example:

## incorrect

**Logitech F310 Controller** 
evtest code for "start ": 315
input_exit_emulator_btn = "7"

evtest code for "home": 316
input_enable_hotkey_btn = "8"

((16#130 + 10#7)) = 311
((16#130 + 10#8)) = 312

**Microsoft Xbox Controller (Original Xbox)**

evtest code for "start ": 315
input_exit_emulator_btn = "7"

evtest code for "select": 314
input_enable_hotkey_btn = "6"

((16#130 + 10#7)) = 311
((16#130 + 10#6)) = 310

**8biddo SF30**

evtest code for "start ": 315
input_exit_emulator_btn = "7"

evtest code for "mode": 314
input_enable_hotkey_btn = "8"

((16#130 + 10#7)) = 311
((16#130 + 10#8)) = 312

**Xbox 360 Gamepad**

evtest code for "start ": 315
input_exit_emulator_btn = "7"

evtest code for "mode": 314
input_enable_hotkey_btn = "8"

((16#130 + 10#7)) = 311
((16#130 + 10#8)) = 312


## Correct

**Hori switch pad** 

evtest code for "start ": 313
input_exit_emulator_btn = "9"

evtest code for "home": 316
input_enable_hotkey_btn = "12"

((16#130 + 10#9)) = 313
((16#130 + 10#8)) = 316

**Retropad Adapter** 

evtest code for "start ": 313
input_exit_emulator_btn = "9"

evtest code for "select": 312
input_enable_hotkey_btn = "8"

((16#130 + 10#9)) = 313
((16#130 + 10#8)) = 312

**Comment by shantigilbert** [comment]
Bump @BetaXOi

**Pull request closed without merging**
